Many if's

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -55,5 +55,12 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
     - name: Check on failures
-      if: ${{ steps.credentials.outcome }} == 'failure' || ${{ steps.login-ecr.outcome }} == 'failure' || ${{ steps.build-image.outcome }} == 'failure'
+      if: ${{ steps.credentials.outcome }} == 'failure'
+      echo: "credentials ${{ steps.credentials.outcome }}"
+      run: exit 1
+      if: ${{ steps.login-ecr.outcome }} == 'failure'
+      echo: "login ${{ steps.login-ecr.outcome }}"
+      run: exit 1
+      if: ${{ steps.build-image.outcome }} == 'failure'
+      echo: "build ${{ steps.build-image.outcome }}"
       run: exit 1
